config/routes.rb
Rails.application.routes.draw do
    get '/', to:'blogs#top'
    get '/blogs', to: 'blogs#index' 
    resources :blogs do
        collection do
          post :confirm
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true,length: {maximum: 140 }
    validates :content, presence: true,length: {maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
      # binding.pry
  end
  
  
  def top
  end
  
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  
  def show
     @blog = Blog.find(params[:id])
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end
  
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end
  
  def create
    @blog = Blog.create(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      render 'new'
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  
  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<div class="contentBlock container-fluid">
  <%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="blog_title col-xs-12 col-sm-6 col-md-6">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title col-xs-12 col-sm-6 col-md-6">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="text-center"><%= form.submit "投稿する" ,:class=>"submitBtn"%></div>
  
 </div>
<% end %>
<div class="text-center">
<%= link_to "ブログ一覧画面にもどる", blogs_path, class: 'btn btn-info'  %>
</div>
</div>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p class="content">タイトル:<%= @blog.title %></p>
  <p class="content">本文:<%= @blog.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1 class="indexTitle text-center">ブログ一覧</h1>

<p><%= notice %></p>

<div class="container">
   <div class="row">
    <!--<th>タイトル</th>-->
    <!--<th>内容</th>-->
 

<% @blogs.each do |blog| %>

 <div class="margin col-xs-12 col-md-6 blog-panel">
    <h3><%= blog.title %></h3>
    <p><%= blog.content %></p>
    <span><%= link_to '詳細を確認する', blog_path(blog.id),class: 'btn btn-info' %></span>
    <span><%= link_to "ブログを編集する", edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？' },class:'btn btn-success'%></span>
    <span><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } ,class:"btn btn-warning"%></span>
</div>
<% end %>
</div>


<p class="newPost"><%= link_to '新しくブログを投稿する', new_blog_path %></p>
</div>

<!--<nav class="navbar navbar-default">-->
<!--  <div class="container-fluid">-->
<!--    <div class="navbar-header">-->
<!--      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">-->
<!--        <span class="sr-only">Bootstrap</span>-->
<!--        <span class="icon-bar"></span>-->
<!--        <span class="icon-bar"></span>-->
<!--        <span class="icon-bar"></span>-->
<!--      </button>-->
<!--      <a class="navbar-brand" href="#">Bootstrap-->

<!--      </a>-->
<!--    </div>-->
<!--    <div id="gnavi" class="collapse navbar-collapse">-->
<!--      <ul class="nav navbar-nav">-->
<!--        <li><a href="">top</a></li>-->
<!--        <li><a href="">menu1</a></li>-->
<!--        <li><a href="">menu2</a></li>-->
<!--      </ul>-->
<!--    </div>-->
<!--  </div>-->
<!--</nav>-->

app/views/blogs/new.html.erb
<h2 class="text-center">ブログを作成する</h2>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細</h1>
<p class="content">タイトル: <%= @blog.title %></p>
<p class="content">内容: <%= @blog.content %></p>
<p><%= link_to "ブログ一覧画面にもどる", blogs_path %></p>

app/views/blogs/top.html.erb
<div class="topWrapper text-center container-fluid">
    <div class="topBackground">
        <div class="topBlock">
            <h1 class="mainTitle">Our Blogs</h1>
        </div>
    </div>
    <div class="appDescription">
        <p class="text-center">これはユーザーが思い思いのブログを投稿できるブログサービスです。</p>
        <p class="text-center">みなさん投稿してね</p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header container-fluid">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only"><a href="/">Our Blogs</a></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Our Blogs</a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">HOME</a></li>
            <li><a href="/blogs/new">新規登録</a></li>
            <li><a href="/blogs">投稿一覧</a></li>
          </ul>
        </div>
      </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
       <p class="text-center"> © 2018 OurBlogs All rights reserved.</p>
    </footer>
  </body>
</html>